lsjob(8)
A manpage for B<job> - the Linux Batch Facility.

=head1 NAME

lsjob - List job attributes

=head1 SYNOPSIS

lsjob I<options> I<job_id>

=head1 DESCRIPTION

***TODO***

=head1 OPTIONS

Mandatory arguments to long options are mandatory for short options too.

=over

=item -h, --help

Show this help message and exit.

=item -R, --root-dir DIR

Root directory of filesystem, default is /.
Queues will be placed under var/spool/job starting at this root.
If you need an entirely different location for the job queues,
consider softlinking to this location.  This option mostly used
for testing.

=item  -t, --max-tries NUM

Set the default maximum number of tries for the job to NUM.

=item -v, --verbose

Show more output.

=back

=head1 EXAMPLES

***TODO***

=head1 SEE ALSO

job(7), jobman(8), edjobq(5), lsjobq(8), mkjobq(8), rmjobq(8), catjob(8), edjob(8), mkjob(8), rmjob(8)

=head1 BUGS

Use the issue tracker at L<https://github.com/spook/job> .  
Don't be shy; check what's already reported and if you have a new bug,
please let me know!

=head1 COPYRIGHT

LGPL 2.1+

job - the Linux Batch Facility
(c) Copyright 2014-2016 Hewlett Packard Enterprise Development LP
Created by Uncle Spook <spook(at)MisfitMountain(dot)org>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
USA

